# ¿Cómo y dónde gasta el Estado chileno a través de Mercado Público, y dónde están las mejores oportunidades para un proveedor? #

In [591]:
#importamos librerias

import pandas as pd
import numpy as np

#Dado que los archivos tiene la misma estructura uso glob.

import glob


archivos = glob.glob('C:/Users/OAD/Documents/mercado-publico-eda/data/raw/*.csv')
df = pd.concat([pd.read_csv(f, sep=';', encoding='Latin-1') for f in archivos], ignore_index=True)

C:\Users\OAD\AppData\Local\Temp\ipykernel_3344\2173574882.py:12: DtypeWarning: Columns (21,31,53,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f, sep=';', encoding='Latin-1') for f in archivos], ignore_index=True)
C:\Users\OAD\AppData\Local\Temp\ipykernel_3344\2173574882.py:12: DtypeWarning: Columns (21,31,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f, sep=';', encoding='Latin-1') for f in archivos], ignore_index=True)
C:\Users\OAD\AppData\Local\Temp\ipykernel_3344\2173574882.py:12: DtypeWarning: Columns (21,31,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f, sep=';', encoding='Latin-1') for f in archivos], ignore_index=True)

*Chequeamos duplicados perfectos*

In [592]:
#Borramos entradas duplicadas
print(df.duplicated().sum().sum())

0

*No existen entradas duplicadas en el dataset.*

In [593]:
df.shape #Comprobamos shape

(1124505, 78)

In [594]:
df.columns.tolist() #Chequeamos columnas.

['ID',
 'Codigo',
 'Link',
 'Nombre',
 'Descripcion/Obervaciones',
 'Tipo',
 'ProcedenciaOC',
 'EsTratoDirecto',
 'EsCompraAgil',
 'CodigoTipo',
 'CodigoAbreviadoTipoOC',
 'DescripcionTipoOC',
 'codigoEstado',
 'Estado',
 'codigoEstadoProveedor',
 'EstadoProveedor',
 'FechaCreacion',
 'FechaEnvio',
 'FechaSolicitudCancelacion',
 'fechaUltimaModificacion',
 'FechaAceptacion',
 'FechaCancelacion',
 'tieneItems',
 'PromedioCalificacion',
 'CantidadEvaluacion',
 'MontoTotalOC',
 'TipoMonedaOC',
 'MontoTotalOC_PesosChilenos',
 'Impuestos',
 'TipoImpuesto',
 'Descuentos',
 'Cargos',
 'TotalNetoOC',
 'CodigoUnidadCompra',
 'RutUnidadCompra',
 'UnidadCompra',
 'CodigoOrganismoPublico',
 'OrganismoPublico',
 'sector',
 'ActividadComprador',
 'CiudadUnidadCompra',
 'RegionUnidadCompra',
 'PaisUnidadCompra',
 'CodigoSucursal',
 'RutSucursal',
 'Sucursal',
 'CodigoProveedor',
 'NombreProveedor',
 'ActividadProveedor',
 'ComunaProveedor',
 'RegionProveedor',
 'PaisProveedor',
 'Financiamiento',
 'PorcentajeIva',
 'Pais',
 'TipoDespacho',
 'FormaPago',
 'CodigoLicitacion',
 'Codigo_ConvenioMarco',
 'IDItem',
 'codigoCategoria',
 'Categoria',
 'codigoProductoONU',
 'NombreroductoGenerico',
 'RubroN1',
 'RubroN2',
 'RubroN3',
 'EspecificacionComprador',
 'EspecificacionProveedor',
 'cantidad',
 'UnidadMedida',
 'monedaItem',
 'precioNeto',
 'totalCargos',
 'totalDescuentos',
 'totalImpuestos',
 'totalLineaNeto',
 'Forma de Pago']

*Se consideran las columnas utiles para el analisis.*
*Se crea una nueva tabla con las columnas utiles para su posterior limpieza y validación*

In [595]:
print("IDs unicas :", df["ID"].nunique())
print("Filas totales :", df.shape[0])

IDs unicas : 401077
Filas totales : 1124505

In [596]:
cols = ['ID', 'OrganismoPublico', "Estado", 'sector', 'FechaEnvio', 'NombreProveedor', "CodigoProveedor", 'ActividadProveedor', 'Categoria', 'RubroN1', "RegionUnidadCompra", "TipoMonedaOC", "totalLineaNeto"]
df_limpieza = df[cols].copy()
df_limpieza.sample(20) #Se verifica la creación de la nueva tabla.

,ID,OrganismoPublico,Estado,sector,FechaEnvio,NombreProveedor,CodigoProveedor,ActividadProveedor,Categoria,RubroN1,RegionUnidadCompra,TipoMonedaOC,totalLineaNeto
608458,54350666,SERVICIO NACIONAL DE PREVENCIÓN Y RESPUESTA AN...,Aceptada,"Gob. Central, Universidades",2026-02-19,HELICOPTEROS DEL PACIFICO LIMITADA,20070,OTRAS ACTIVIDADES DE SERVICIOS CONEXAS A LA SI...,"Servicios de transporte, almacenaje y correo /...","Servicios de transporte, almacenaje y correo",Región Metropolitana de Santiago,CLP,"28212006,396"
1031899,54526696,HOSPITAL INTERCULTURAL KALLVU LLANKA.-,Recepcion Conforme,Salud,2026-03-24,CAVIMED de CHILE SPA,1449686,Venta insumos médicos,Equipamiento y suministros médicos / Productos...,Equipamiento y suministros médicos,Región del Biobío,CLP,23500
847520,54443152,SERVICIO DE SALUD OCCIDENTE INSTITUTO TRAUMATO...,Recepcion Conforme,Salud,2026-03-12,CAROL ANDREA SAN MARTÍN VÁSQUEZ,38274,IMPRESION PRINCIPALMENTE DE LIBROS| ACTIVIDADE...,Productos de papel / Productos de papel / Pape...,Productos de papel,Región Metropolitana de Santiago,CLP,130000
1027506,54524747,I MUNICIPALIDAD DE SAN CLEMENTE,Recepcion Conforme,Municipalidades,2026-03-23,Ester del Carmen,1645347,"servicio de banqueteria, catering y otras cele...","Servicios profesionales, administrativos y con...","Servicios profesionales, administrativos y con...",Región del Maule,CLP,840336
883451,54457517,I MUNICIPALIDAD DE FLORIDA,Aceptada,Municipalidades,2026-03-11,COMERCIALIZADORA JUANA CAMPOS HERNANDEZ SPA,1553761,"fab. colchones, ropa de cama, muebles y art. p...","Muebles, accesorios, electrodomésticos y produ...","Muebles, accesorios, electrodomésticos y produ...",Región del Biobío,CLP,58822
423380,54267020,Ilustre Municipalidad de Lumaco,Aceptada,Municipalidades,2026-02-03,VICTORINA DEL CARMEN MONTENEGRO RÍOS,225747,VENTA AL POR MENOR EN EMPRESAS DE VENTA A DIST...,"Equipos y suministros de defensa, orden públic...","Equipos y suministros de defensa, orden públic...",Región de la Araucanía,CLP,36000
371927,54223711,I MUNICIPALIDAD DE TEMUCO,Aceptada,Municipalidades,2026-02-08,Comercial Masol Ltda.,1008285,Comercial,NaN,NaN,Región de la Araucanía,CLP,70400
585411,54339343,I MUNICIPALIDAD DE TOCOPILLA,Aceptada,Municipalidades,2026-02-17,IFRIT COMERCIAL SPA,1820608,VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCI...,Artículos de fabricación y producción / Artícu...,Artículos de fabricación y producción,Región de Antofagasta,CLP,18000
1002643,54510931,I MUNICIPALIDAD DE COLLIPULLI,Recepcion Conforme,Municipalidades,2026-03-27,INGRID XIMENA SAAVEDRA GÓMEZ,214990,VENTA AL POR MENOR DE OTROS PRODUCTOS EN PEQUE...,NaN,NaN,Región de la Araucanía,CLP,34650
334134,54242304,HOSPITAL BASE OSORNO,Aceptada,Salud,2026-01-29,DROGUERIA HOFMANN SAC,39998,VENTA AL POR MAYOR DE PRODUCTOS QUIMICOS| VENT...,Equipamiento y suministros médicos / Productos...,Equipamiento y suministros médicos,Región de los Lagos,CLP,2200
545087,54322657,DIRECCION DE ABASTECIMIENTO DE LA ARMADA,Recepcion Conforme,FFAA,2026-02-13,SOCIEDAD PROVEEDORA INDUSTRIAL MANTIN & SERVIC...,130168,VENTA AL POR MAYOR DE OTROS PRODUCTOS N.C.P.| ...,Artículos de fabricación y producción / Cintas...,Artículos de fabricación y producción,Región de Valparaíso,CLP,557400
395398,54255628,I MUNICIPALIDAD DE HIJUELAS,Recepcion Conforme,Municipalidades,2026-02-02,COMERCIAL GBG SPA,1798212,VENTA AL POR MAYOR DE PRODUCTOS FARMACEUTICOS ...,Equipamiento y suministros médicos / Vestuario...,Equipamiento y suministros médicos,Región de Valparaíso,CLP,13000
828967,54435628,DIRECCION DE LOGISTICA DE CARABINEROS,Recepcion Conforme,FFAA,2026-03-11,ALIPRES SPA,1539123,ELABORACION Y COMERCIALIZACION DE FRUTAS Y VER...,NaN,NaN,Región de los Lagos,CLP,29280
300246,54222705,HOSPITAL SANTA ELISA DE SAN JOSE DE LA MARIQUINA,Recepcion Conforme,Salud,2026-01-27,Diprolab Ltda.,39563,COMERCIAL,"Artículos para estructuras, obras y construcci...","Artículos para estructuras, obras y construcci...",Región de Los Ríos,CLP,336000
801467,54423243,SERVICIO AGRICOLA Y GANADERO,Aceptada,"Gob. Central, Universidades",2026-03-16,JAIME EDUARDO,1402180,VENTA AL POR MAYOR DE INSTRUMENTOS CIENTIFICOS...,Artículos de fabricación y producción / Cintas...,Artículos de fabricación y producción,Región de la Araucanía,CLP,48000
898229,54464629,SERVICIO DE SALUD HOSPITAL DE SAN FERNANDO,Aceptada,Salud,2026-03-12,Bruno Antonio Canales Rodriguez,1814646,Persona Natural,"Servicios profesionales, administrativos y con...","Servicios profesionales, administrativos y con...",Región del Libertador General Bernardo O´Higgins,CLP,"450022,5"
868318,54451102,DIVISION LOGISTICA DEL EJERCITO,Recepcion Conforme,FFAA,2026-03-12,INVERSIONES VALDERRAMA SPA,1990469,VENTA AL POR MENOR DE ARTICULOS DE PAPELERIA Y...,"Artículos para estructuras, obras y construcci...","Artículos para estructuras, obras y construcci...",Región de Tarapacá,CLP,49000
875809,54454254,SERVICIO DE SALUD ARICA HOSP DR JUAN NOE CREVANI,Aceptada,Salud,2026-03-11,SKY AIRLINE S A,71217,TRANSPORTE REGULAR POR VIA AEREA DE PASAJEROS|...,NaN,NaN,Región de Arica y Parinacota,CLP,121491
176099,54164183,HOSPITAL CLINICO METROPOLITANO EL CARMEN DOCTO...,Recepcion Conforme,Salud,2026-01-16,TECNOMEDICAL S A,135817,VENTA AL POR MAYOR DE OTROS PRODUCTOS N.C.P.,Equipamiento y suministros médicos / Productos...,Equipamiento y suministros médicos,Región Metropolitana de Santiago,CLP,34500
113067,54133704,SERVICIO DE SALUD ARICA HOSP DR JUAN NOE CREVANI,Aceptada,Salud,2026-01-09,SKY AIRLINE S A,71217,TRANSPORTE REGULAR POR VIA AEREA DE PASAJEROS|...,NaN,NaN,Región de Arica y Parinacota,CLP,206091

In [597]:
column_mapping = {
    "ID": "id",
    "OrganismoPublico": "organismo_publico",
    "Estado": "estado",
    "sector": "sector",
    "FechaEnvio": "fecha_envio",
    "NombreProveedor": "nombre_proveedor",
    "CodigoProveedor": "codigo_de_proveedor",
    "ActividadProveedor": "actividad_proveedor",
    "Categoria": "categoria",
    "RubroN1": "rubro",
    "RegionUnidadCompra": "region_de_compra",
    "TipoMonedaOC": "tipo_moneda_oc",
    "totalLineaNeto": "total_linea_neto",
}
df = df.rename(columns=column_mapping)

columns_cleaning = [
    "id",
    "organismo_publico",
    "estado",
    "sector",
    "fecha_envio",
    "nombre_proveedor",
    "codigo_de_proveedor",
    "actividad_proveedor",
    "categoria",
    "rubro",
    "region_de_compra",
    "tipo_moneda_oc",
    "total_linea_neto",
]

df_limpieza = df[columns_cleaning]

In [598]:
df_limpieza.sample(8)

,id,organismo_publico,estado,sector,fecha_envio,nombre_proveedor,codigo_de_proveedor,actividad_proveedor,categoria,rubro,region_de_compra,tipo_moneda_oc,total_linea_neto
304634,54224699,Corporación Municipal de Deporte de Vitacura,Aceptada,Otros,2026-01-27,CIBERCONSULTING CHILE SPA,2074060,ACTIVIDADES DE ASOCIACIONES PROFESIONALES,"Equipos, accesorios y suministros de oficina /...","Equipos, accesorios y suministros de oficina",Región Metropolitana de Santiago,CLP,31680
572763,54334027,SERVICIO DE SALUD ATACAMA HOSPITAL COPIA,Recepcion Conforme,Salud,2026-02-16,HOSPITALIA PRODUCTOS MEDICOS LTDA,69350,VENTA AL POR MAYOR DE OTROS PRODUCTOS N.C.P.,Equipamiento y suministros médicos / Productos...,Equipamiento y suministros médicos,Región de Atacama,CLP,301860
445015,54278640,SERVICIO LOCAL DE EDUCACIÓN PÚBLICA DE CHILOÉ,Recepcion Conforme,NaN,2026-02-09,VALERIA YANET DÍAZ CARTES,1520922,TURISMO Y TRANSPORTE,"Servicios de transporte, almacenaje y correo /...","Servicios de transporte, almacenaje y correo",Región de los Lagos,CLP,"2,4e+07"
579092,54336687,SERVICIO DE SALUD COQUIMBO HOSPITAL LA SERENA,Recepcion Conforme,Salud,2026-02-17,Therapía iv,66973,"FABRICACION DE PRODUCTOS FARMACEUTICOS, SUSTAN...",Equipamiento y suministros médicos / Nutrición...,Equipamiento y suministros médicos,Región de Coquimbo,CLP,336000
1107580,54561393,DIVISION LOGISTICA DEL EJERCITO,Recepcion Conforme,FFAA,2026-03-30,ARENYS MED S.A.,265250,OTRAS ACTIVIDADES EMPRESARIALES RELACIONADAS C...,Equipamiento y suministros médicos / Productos...,Equipamiento y suministros médicos,Región Metropolitana de Santiago,CLP,49404
690453,54389714,SERVICIO DE SALUD VALDIVIA HOSPITAL LA U,Recepcion Conforme,Salud,2026-02-27,HOSPITALIA PRODUCTOS MEDICOS LTDA,69350,VENTA AL POR MAYOR DE OTROS PRODUCTOS N.C.P.,NaN,NaN,Región de Los Ríos,CLP,612200
948736,54487063,I MUNICIPALIDAD DE LAS GUAITECAS,Aceptada,Municipalidades,2026-03-18,KRAKEN SPA,1788219,"VENTA AL POR MENOR DE COMPUTADORES, EQUIPO PER...","Tecnologías de la información, telecomunicacio...","Tecnologías de la información, telecomunicacio...",Región Aysén del General Carlos Ibáñez del Campo,CLP,1100000
356936,54112696,SERVICIO DE SALUD DEL MAULE HOSPITAL DE LICANTEN,Aceptada,Salud,2026-02-04,I-MED S.A.,47799,ACTIVIDADES DE ASESORAMIENTO EMPRESARIAL Y EN ...,"Tecnologías de la información, telecomunicacio...","Tecnologías de la información, telecomunicacio...",Región del Maule,CLP,320

*Dtypes*

In [599]:
df_limpieza.dtypes

id                      int64
organismo_publico      object
estado                 object
sector                 object
fecha_envio            object
nombre_proveedor       object
codigo_de_proveedor     int64
actividad_proveedor    object
categoria              object
rubro                  object
region_de_compra       object
tipo_moneda_oc         object
total_linea_neto       object
dtype: object

In [600]:
df_limpieza["total_linea_neto"] = pd.to_numeric(
    df_limpieza["total_linea_neto"].str.replace(",", ".")
)
df_limpieza["total_linea_neto"] = pd.to_numeric(df_limpieza["total_linea_neto"])
df_limpieza["fecha_envio"] = pd.to_datetime(df_limpieza["fecha_envio"], format="%Y-%m-%d")

C:\Users\OAD\AppData\Local\Temp\ipykernel_3344\3913384357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpieza["total_linea_neto"] = pd.to_numeric(
C:\Users\OAD\AppData\Local\Temp\ipykernel_3344\3913384357.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpieza["total_linea_neto"] = pd.to_numeric(df_limpieza["total_linea_neto"])
C:\Users\OAD\AppData\Local\Temp\ipykernel_3344\3913384357.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpieza["fecha_envio"] = pd.to_datetime(df_limpieza["fecha_envio"], format="%Y-%m-%d")

In [601]:
print(df_limpieza["fecha_envio"].dtypes)
print(df_limpieza["total_linea_neto"].dtypes)

datetime64[ns]
float64

In [602]:
df_limpieza["sector"].value_counts()

sector
Salud                          462792
Municipalidades                326129
Gob. Central, Universidades    134244
FFAA                           119671
Otros                           28088
Obras Públicas                   7966
Legislativo y judicial           6919
Name: count, dtype: int64

In [603]:
df_limpieza["estado"].value_counts()

estado
Recepcion Conforme        821530
Aceptada                  292844
Enviada a proveedor         8334
Cancelacion solicitada      1100
En proceso                   697
Name: count, dtype: int64

In [604]:
df_limpieza_estado_clear = df_limpieza[~df_limpieza["estado"].isin(["Cancelacion solicitada", "En proceso"])]
df_limpieza = df_limpieza_estado_clear

In [605]:
df_limpieza["estado"].value_counts()

estado
Recepcion Conforme     821530
Aceptada               292844
Enviada a proveedor      8334
Name: count, dtype: int64

In [606]:
df_limpieza["tipo_moneda_oc"].value_counts()

tipo_moneda_oc
CLP    1116249
CLF       3463
USD       2787
UTM        193
EUR         16
Name: count, dtype: int64

In [607]:
df_limpieza["tipo_moneda_oc"].value_counts(normalize=True) * 100

tipo_moneda_oc
CLP    99.424695
CLF     0.308451
USD     0.248239
UTM     0.017191
EUR     0.001425
Name: proportion, dtype: float64

In [608]:
valor_uf = 40844
es_clf = df_limpieza["tipo_moneda_oc"] == "CLF"
df_limpieza.loc[es_clf, "total_linea_neto"] *= df_limpieza.loc[es_clf, "total_linea_neto"] * valor_uf
df_limpieza.loc[es_clf, "tipo_moneda_oc"] = "CLP"

valor_usd = 947
es_usd = df_limpieza["tipo_moneda_oc"] == "USD"
df_limpieza.loc[es_usd, "total_linea_neto"] *= df_limpieza.loc[es_usd, "total_linea_neto"] * valor_usd
df_limpieza.loc[es_usd, "tipo_moneda_oc"] = "CLP"

valor_utm = 71649
es_utm = df_limpieza["tipo_moneda_oc"] == "UTM"
df_limpieza.loc[es_utm, "total_linea_neto"] *= df_limpieza.loc[es_utm, "total_linea_neto"] * valor_utm
df_limpieza.loc[es_utm, "tipo_moneda_oc"] = "CLP"

valor_eur = 1076
es_eur = df_limpieza["tipo_moneda_oc"] == "EUR"
df_limpieza.loc[es_eur, "total_linea_neto"] *= df_limpieza.loc[es_eur, "total_linea_neto"] * valor_eur
df_limpieza.loc[es_eur, "tipo_moneda_oc"] = "CLP"

In [609]:
df_limpieza["tipo_moneda_oc"].value_counts(normalize=True) * 100

tipo_moneda_oc
CLP    100.0
Name: proportion, dtype: float64

In [610]:
df_limpieza.dtypes

id                              int64
organismo_publico              object
estado                         object
sector                         object
fecha_envio            datetime64[ns]
nombre_proveedor               object
codigo_de_proveedor             int64
actividad_proveedor            object
categoria                      object
rubro                          object
region_de_compra               object
tipo_moneda_oc                 object
total_linea_neto              float64
dtype: object

*Outliers*

In [611]:
df_limpieza["total_linea_neto"].describe()

count    1.122701e+06
mean     7.768993e+11
std      7.581645e+14
min     -1.474011e+07
25%      3.600000e+04
50%      1.500000e+05
75%      6.508450e+05
max      8.031431e+17
Name: total_linea_neto, dtype: float64

In [612]:
def formato_clp(valor, acronimo=True):
    if valor is None or pd.isna(valor):
        return ""

    # Opción 1: Resumido en Millones (muy común en análisis financiero en Chile)
    if acronimo and abs(valor) >= 1_000_000:
        return f"${valor / 1_000_000:,.1f}M".replace(",", "X").replace(".", ",").replace("X", ".")

    # Opción 2: Cifra entera con separador de miles chileno ($ 1.250.000)
    return f"${int(round(valor)):,}".replace(",", ".")

In [613]:
df_limpieza = df_limpieza[df_limpieza["total_linea_neto"] >= 0]

In [614]:
df_limpieza.sort_values(by="total_linea_neto", ascending=False)

,id,organismo_publico,estado,sector,fecha_envio,nombre_proveedor,codigo_de_proveedor,actividad_proveedor,categoria,rubro,region_de_compra,tipo_moneda_oc,total_linea_neto
376317,54234357,I MUNICIPALIDAD DE RIO BUENO,Enviada a proveedor,Municipalidades,2026-02-13,AUTORENTAS DEL PACIFICO SPA,24629,ALQUILER DE AUTOS Y CAMIONETAS SIN CHOFER,"Servicios de transporte, almacenaje y correo /...","Servicios de transporte, almacenaje y correo",Región de Los Ríos,CLP,8.031431e+17
384184,54246886,SUBSECRETARIA DE SALUD PUBLICA,Recepcion Conforme,Salud,2026-02-03,EMPRESA NACIONAL DE TELECOMUNICACIONES S A,41738,OTROS SERVICIOS DE TELECOMUNICACIONES N.C.P.,"Servicios basados en ingeniería, ciencias soci...","Servicios basados en ingeniería, ciencias soci...",Región Metropolitana de Santiago,CLP,1.071691e+16
716667,54288307,JUNTA NACIONAL DE JARDINES INFANTILES,Aceptada,"Gob. Central, Universidades",2026-03-23,SONDA S A,24685,EMPRESAS DE SERVICIOS INTEGRALES DE INFORMATICA,"Tecnologías de la información, telecomunicacio...","Tecnologías de la información, telecomunicacio...",Región Metropolitana de Santiago,CLP,9.212089e+15
677119,54381649,DIRECCION DE LOGISTICA DE CARABINEROS,Recepcion Conforme,FFAA,2026-02-25,CLOUDHESIVE CHILE SPA,1706756,"VENTA AL POR MAYOR DE COMPUTADORES, EQUIPO PER...","Tecnologías de la información, telecomunicacio...","Tecnologías de la información, telecomunicacio...",Región Metropolitana de Santiago,CLP,5.516647e+15
29720,54061160,I MUNICIPALIDAD DE LAS CONDES,Aceptada,Municipalidades,2026-01-24,EnorChile,61682,FABRICACION DE MOTORES Y TURBINAS| FABRICACION...,Servicios básicos y de información pública / S...,Servicios básicos y de información pública,Región Metropolitana de Santiago,CLP,5.361070e+15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39008,54092742,DIRECCION DE ABASTECIMIENTO DE LA ARMADA,Recepcion Conforme,FFAA,2026-01-07,CENTRO DE DIAGNOSTICO CLINICA MAGALLANES SPA,1242129,-,"Salud, servicios sanitarios y alimentación / M...","Salud, servicios sanitarios y alimentación",Región de Magallanes y de la Antártica,CLP,0.000000e+00
53528,54104352,I MUNICIPALIDAD DE LOS MUERMOS,Recepcion Conforme,Municipalidades,2026-01-05,ANVIC INGENIERIA E INSPECCIÓN LTDA,1444273,SERVICIOS PROFESIONALES,Consultoria / Consultoria / Arquitectura y Urb...,Consultoria,Región de los Lagos,CLP,0.000000e+00
883833,54457609,I MUNICIPALIDAD DE SANTO DOMINGO,Recepcion Conforme,Municipalidades,2026-03-11,LUIS EDUARDO VERA CATALÁN,1731139,NaN,"Servicios de transporte, almacenaje y correo /...","Servicios de transporte, almacenaje y correo",Región de Valparaíso,CLP,0.000000e+00
371255,54221912,SUBSECRETARIA DEL MINISTERIO DE EDUCACION PUBLICA,Aceptada,"Gob. Central, Universidades",2026-02-13,EMPRESA DE CORREOS DE CHILE,16120,OTROS SERVICIOS DE TELECOMUNICACIONES N.C.P.,"Servicios de transporte, almacenaje y correo /...","Servicios de transporte, almacenaje y correo",Región del Biobío,CLP,0.000000e+00
706920,54399669,CORP CULTURAL Y TURISMO DE CALAMA,Aceptada,NaN,2026-02-28,Felipe Mateo,1554810,"Producción de eventos, servicio de producción ...","Servicios profesionales, administrativos y con...","Servicios profesionales, administrativos y con...",Región de Antofagasta,CLP,0.000000e+00

*"I MUNICIPALIDAD DE RIO BUENO" es una localidad con 33.013 habitantes, sin embargo tiene un gasto absurdo que probablemente sea error de typeo. Se procede a comprobar.*

In [615]:
df_limpieza_posibles_outliers = (df_limpieza[df_limpieza["nombre_proveedor"] == "AUTORENTAS DEL PACIFICO SPA"])

In [616]:
df_limpieza_posibles_outliers["total_linea_neto"].sort_values(ascending=False).apply(formato_clp)

376317     $803.143.050.694,5M
410290           $2.577.002,8M
891253              $91.754,6M
104367              $66.959,4M
554563              $37.439,5M
                  ...
213575                  $7.930
222956                  $7.875
222986                  $7.875
1026068                 $6.609
1026067                   $525
Name: total_linea_neto, Length: 124, dtype: object

In [617]:
# Nota los dobles corchetes [[ ]]
df_limpieza.loc[376317]

id                                                              54234357
organismo_publico                           I MUNICIPALIDAD DE RIO BUENO
estado                                               Enviada a proveedor
sector                                                   Municipalidades
fecha_envio                                          2026-02-13 00:00:00
nombre_proveedor                             AUTORENTAS DEL PACIFICO SPA
codigo_de_proveedor                                                24629
actividad_proveedor            ALQUILER DE AUTOS Y CAMIONETAS SIN CHOFER
categoria              Servicios de transporte, almacenaje y correo /...
rubro                       Servicios de transporte, almacenaje y correo
region_de_compra                                      Región de Los Ríos
tipo_moneda_oc                                                       CLP
total_linea_neto                                    803143050694503296.0
Name: 376317, dtype: object

*El numero no calza con ningún RUT, orden de compra, id, y tampoco se atribuye un error de lectura producto de puntación de miles (, o .). Se procede a descartar dado que es considerado error de tipeo.*

In [618]:
df_limpieza = df_limpieza.drop(376317)

In [619]:
df_limpieza.sort_values(by="total_linea_neto", ascending=False)

,id,organismo_publico,estado,sector,fecha_envio,nombre_proveedor,codigo_de_proveedor,actividad_proveedor,categoria,rubro,region_de_compra,tipo_moneda_oc,total_linea_neto
384184,54246886,SUBSECRETARIA DE SALUD PUBLICA,Recepcion Conforme,Salud,2026-02-03,EMPRESA NACIONAL DE TELECOMUNICACIONES S A,41738,OTROS SERVICIOS DE TELECOMUNICACIONES N.C.P.,"Servicios basados en ingeniería, ciencias soci...","Servicios basados en ingeniería, ciencias soci...",Región Metropolitana de Santiago,CLP,1.071691e+16
716667,54288307,JUNTA NACIONAL DE JARDINES INFANTILES,Aceptada,"Gob. Central, Universidades",2026-03-23,SONDA S A,24685,EMPRESAS DE SERVICIOS INTEGRALES DE INFORMATICA,"Tecnologías de la información, telecomunicacio...","Tecnologías de la información, telecomunicacio...",Región Metropolitana de Santiago,CLP,9.212089e+15
677119,54381649,DIRECCION DE LOGISTICA DE CARABINEROS,Recepcion Conforme,FFAA,2026-02-25,CLOUDHESIVE CHILE SPA,1706756,"VENTA AL POR MAYOR DE COMPUTADORES, EQUIPO PER...","Tecnologías de la información, telecomunicacio...","Tecnologías de la información, telecomunicacio...",Región Metropolitana de Santiago,CLP,5.516647e+15
29720,54061160,I MUNICIPALIDAD DE LAS CONDES,Aceptada,Municipalidades,2026-01-24,EnorChile,61682,FABRICACION DE MOTORES Y TURBINAS| FABRICACION...,Servicios básicos y de información pública / S...,Servicios básicos y de información pública,Región Metropolitana de Santiago,CLP,5.361070e+15
885472,54458365,INSTITUTO DE PREVISION SOCIAL,Recepcion Conforme,"Gob. Central, Universidades",2026-03-11,CAJA DE COMPENSACION DE ASIGNACION FAMIL,17788,GOBIERNO CENTRAL| CAJAS DE COMPENSACION,"Servicios financieros, pensiones y seguros / B...","Servicios financieros, pensiones y seguros",Región Metropolitana de Santiago,CLP,3.055581e+15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53528,54104352,I MUNICIPALIDAD DE LOS MUERMOS,Recepcion Conforme,Municipalidades,2026-01-05,ANVIC INGENIERIA E INSPECCIÓN LTDA,1444273,SERVICIOS PROFESIONALES,Consultoria / Consultoria / Arquitectura y Urb...,Consultoria,Región de los Lagos,CLP,0.000000e+00
883833,54457609,I MUNICIPALIDAD DE SANTO DOMINGO,Recepcion Conforme,Municipalidades,2026-03-11,LUIS EDUARDO VERA CATALÁN,1731139,NaN,"Servicios de transporte, almacenaje y correo /...","Servicios de transporte, almacenaje y correo",Región de Valparaíso,CLP,0.000000e+00
39008,54092742,DIRECCION DE ABASTECIMIENTO DE LA ARMADA,Recepcion Conforme,FFAA,2026-01-07,CENTRO DE DIAGNOSTICO CLINICA MAGALLANES SPA,1242129,-,"Salud, servicios sanitarios y alimentación / M...","Salud, servicios sanitarios y alimentación",Región de Magallanes y de la Antártica,CLP,0.000000e+00
676824,54381519,CORPORACION CULTURAL DE MOSTAZAL,Recepcion Conforme,NaN,2026-02-25,LOS VILLANOS DE COLTAUCO SPA,1983550,"OTRAS ACTIVIDADES CREATIVAS, ARTISTICAS Y DE E...","Servicios editoriales, de diseño, publicidad, ...","Servicios editoriales, de diseño, publicidad, ...",Región del Libertador General Bernardo O´Higgins,CLP,0.000000e+00
826335,54434618,SERVICIO SALUD SAN FELIPE LOS ANDES HOSP,Aceptada,Salud,2026-03-06,MARIELA CARLA ROJAS HENRÍQUEZ,1767244,SERVICIOS DE MEDICOS PRESTADOS DE FORMA INDEPE...,"Servicios profesionales, administrativos y con...","Servicios profesionales, administrativos y con...",Región de Valparaíso,CLP,0.000000e+00

In [620]:
df_limpieza["total_linea_neto"].sort_values(ascending=False).apply(formato_clp)

384184    $10.716.907.441,4M
716667     $9.212.088.932,5M
677119     $5.516.647.204,1M
29720      $5.361.069.955,8M
885472     $3.055.580.576,1M
                 ...
53528                     $0
883833                    $0
39008                     $0
676824                    $0
826335                    $0
Name: total_linea_neto, Length: 1122622, dtype: object

*A pesar de haber montos altos estos son aceptables para la naturaleza de mercado publico.*

*Nulos*

In [621]:
df_limpieza.isna().sum()

id                          0
organismo_publico           0
estado                      0
sector                  38673
fecha_envio                 0
nombre_proveedor            0
codigo_de_proveedor         0
actividad_proveedor      9145
categoria              205491
rubro                  205491
region_de_compra            0
tipo_moneda_oc              0
total_linea_neto            0
dtype: int64

---

# Tabla Limpia #

In [626]:
df_limpieza.sample(5)

,id,organismo_publico,estado,sector,fecha_envio,nombre_proveedor,codigo_de_proveedor,actividad_proveedor,categoria,rubro,region_de_compra,tipo_moneda_oc,total_linea_neto
970263,54496268,MINISTERIO DE OBRAS PUBLICAS DIREC CION GRAL D...,Recepcion Conforme,Obras Públicas,2026-03-18,JOSE GUILLERMO FERNANDEZ CHANDIA ALQUILER DE O...,1822348,"CAPTACION, TRATAMIENTO Y DISTRIBUCION DE AGUA","Alimentos, bebidas y tabaco / Bebidas / Bebida...","Alimentos, bebidas y tabaco",Región del Libertador General Bernardo O´Higgins,CLP,71748.0
1028484,54525220,DIRECCION DE ABASTECIMIENTO DE LA ARMADA,Recepcion Conforme,FFAA,2026-03-26,BASTIÁN ALFREDO NÚÑEZ PALMA,1711446,ACTIVIDADES DE SERVICIOS DE SISTEMAS DE SEGURI...,"Equipos y suministros de defensa, orden públic...","Equipos y suministros de defensa, orden públic...",Región de Valparaíso,CLP,80000.0
348612,54251773,HOSPITAL CLINICO HERMINDA MARTIN,Recepcion Conforme,Salud,2026-01-30,COMERCIAL MUÑOZ Y ALAMOS LIMITADA,1816291,TRANSPORTE DE CARGA POR CARRETERA,Servicios de construcción y mantenimiento / Co...,Servicios de construcción y mantenimiento,Región del Ñuble,CLP,115000.0
856675,54446764,SERVICIO SALUD SAN FELIPE LOS ANDES HOSP,Recepcion Conforme,Salud,2026-03-20,GEMCO GENERAL MACHINERY S.A.,113980,FABRICACION DE OTROS TIPOS DE EQUIPO ELECTRICO...,Equipamiento para laboratorios / Equipos e ins...,Equipamiento para laboratorios,Región de Valparaíso,CLP,14075640.0
444322,54278327,I MUNICIPALIDAD DE RENAICO,Recepcion Conforme,Municipalidades,2026-02-05,Inversiones Corp Premier Ltda,1437620,PRESTACIÓN DE SERVICIOS DE RECURSOS TÉCNICOS E...,Artículos eléctricos y de iluminación / Equipa...,Artículos eléctricos y de iluminación,Región de la Araucanía,CLP,21000.0

In [623]:
df_limpieza.shape

(1122622, 13)

In [624]:
df_limpieza["total_linea_neto"] = df_limpieza["total_linea_neto"].astype(float)

df_limpieza.dtypes

id                              int64
organismo_publico              object
estado                         object
sector                         object
fecha_envio            datetime64[ns]
nombre_proveedor               object
codigo_de_proveedor             int64
actividad_proveedor            object
categoria                      object
rubro                          object
region_de_compra               object
tipo_moneda_oc                 object
total_linea_neto              float64
dtype: object

---

# Export #

In [625]:
df_limpieza.to_parquet('C:/Users/OAD/Documents/mercado-publico-eda/data/processed/mercado_publico_eda_clean.parquet', index=False)